---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/Ste100Mark
    about: Read the documentation for Ste100Mark
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/Ste100Mark/discussions
    about: Ask questions and discuss with the community
