package Ste100Mark {
    part def Program {
        doc /* Entry point and execution orchestrator. */

        comment sourceRef /* Source: src/DemaConsulting.Ste100Mark/Program.cs */
        comment testRef /* Test: test/DemaConsulting.Ste100Mark.Tests/ProgramTests.cs */
        comment designRef /* Design: docs/design/ste100-mark/program.md */
        comment verificationRef /* Verification: docs/verification/ste100-mark/program.md */
        comment reqRef /* Requirements: docs/reqstream/ste100-mark/program.yaml */
    }
}
